"""empty message

Revision ID: 835cee15074e
Revises: b1beebe9c3b1
Create Date: 2020-02-28 23:53:14.331994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835cee15074e'
down_revision = 'b1beebe9c3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Artist', 'website',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=700),
               existing_nullable=True)
    op.alter_column('Venue', 'website',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=700),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'website',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('Venue', 'image_link',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('Venue', 'genres',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('Venue', 'facebook_link',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('Artist', 'website',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('Artist', 'image_link',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('Artist', 'genres',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('Artist', 'facebook_link',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
