"""empty message

Revision ID: 8ce2c0383f8b
Revises: 835cee15074e
Create Date: 2020-02-29 11:06:23.153811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce2c0383f8b'
down_revision = '835cee15074e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using='genres::character varying[]')
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using='genres::character varying[]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=sa.ARRAY(sa.String()),
               type_=sa.VARCHAR(length=700),
               existing_nullable=True)
    op.alter_column('Artist', 'genres',
               existing_type=sa.ARRAY(sa.String()),
               type_=sa.VARCHAR(length=700),
               existing_nullable=True)
    # ### end Alembic commands ###
